--- job_types seed data ---
insert into job_types (type,updated_at,created_by,updated_by) values ('IT-Software / Software Services/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('BPO / Call Centre / ITES/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Automobile / Auto Anciliary / Auto Components/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Construction / Engineering / Cement / Metals/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Banking / Financial Services / Broking',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Accounting / Finance/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Advertising / PR / MR / Event Management/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Agriculture / Dairy/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Animation / Gaming/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Architecture / Interior Design/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Aviation / Aerospace Firms/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Brewery / Distillery/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Broadcasting',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Ceramics / Sanitary ware/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Chemicals / PetroChemical / Plastic / Rubber/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Consumer Electronics / Appliances / Durables/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Courier / Transportation / Freight / Warehousing/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Education / Teaching / Training/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Electricals / Switchgears/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Export / Import/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Facility Management/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Fertilizers / Pesticides/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('FMCG / Foods / Beverage/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Food Processing/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Fresher / Trainee / Entry Level/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Gems / Jewellery/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Glass / Glassware/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Government / Defence/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Heat Ventilation / Air Conditioning/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Industrial Products / Heavy Machinery/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Insurance',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Iron and Steel/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('IT-Hardware &amp; Networking/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('KPO / Research / Analytics/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Legal',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Media / Entertainment / Internet/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Internet / Ecommerce/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Leather',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Medical / Healthcare / Hospitals/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Mining / Quarrying/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('NGO / Social Services / Regulators / Industry Associations/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Office Equipment / Automation/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Oil and Gas / Energy / Power / Infrastructure/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Pulp and Paper/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Pharma / Biotech / Clinical Research/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Printing / Packaging/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Publishing',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Real Estate / Property/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Recruitment / Staffing/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Retail / Wholesale/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Security / Law Enforcement/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Semiconductors / Electronics/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Shipping / Marine/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Strategy / Management Consulting Firms/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Sugar',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Telecom/ISP/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Textiles / Garments / Accessories/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Travel / Hotels / Restaurants / Airlines / Railways/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Tyres',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Water Treatment / Waste Management/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Wellness / Fitness / Sports/',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_types (type,updated_at,created_by,updated_by) values ('Other',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');


--- job_functional_area seed data ---

insert into job_functional_area (type,updated_at,created_by,updated_by) values('Sales, Retail, Business Development',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Application Programming, Maintenance',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('ITES, BPO, KPO, LPO, Customer Service, Operations ',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Production, Manufacturing, Maintenance ',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Accounts, Finance, Tax, Company Secretary, Audit',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Analytics &amp; Business Intelligence',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Architecture, Interior Design',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Defence Forces, Security Services',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Design, Creative, User Experience',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Engineering Design, R&amp;D',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Executive Assistant, Front Office, Data Entry',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Export, Import, Merchandising',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Fashion Designing, Merchandising',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Hotels, Restaurants',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('HR, Recruitment, Administration, IR',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Financial Services, Banking, Investments, Insurance',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Hardware, Technical Support, Telecom Engineering',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Client/Server Programming',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - eCommerce, Internet Technologies',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Mainframe ',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Middleware',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Mobile',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Other',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - System Programming',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Telecom Software',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - DBA, Datawarehousing',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Embedded, EDA, VLSI, ASIC, Chip Design',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - ERP, CRM',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Network Administration, Security',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - QA &amp; Testing',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('IT Software - Systems, EDP, MIS',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Journalism, Editing, Content',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Legal, Regulatory, Intellectual Property',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Marketing, Advertising, MR, PR, Media Planning',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Medical, Healthcare, R&amp;D, Pharmaceuticals, Biotechnology',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Packaging',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Self Employed, Entrepreneur, Independent Consultant',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Shipping',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Site Engineering, Project Management',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Strategy, Management Consulting, Corporate Planning',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Supply Chain, Logistics, Purchase, Materials',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Teaching, Education, Training, Counselling',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Top Management',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Travel, Tours, Ticketing, Airlines',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('TV, Films, Production, Broadcasting',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');
insert into job_functional_area (type,updated_at,created_by,updated_by) values('Other',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahho.com');


--- degree_qualifications ---
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Tech/B.E',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('Diploma',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Sc',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Com',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('Graduation Not Required',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('Any Graduate',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.A',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Arch',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.B.A',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Ed',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('B.Pharma',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('BCA',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('BDS',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('BHM',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('BVSC',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('LLB',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('MBBS',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');
insert into degree_qualifications (name,updated_at,created_by,updated_by) values('Other Graduate',now(),'kirit_bellubbi@yahoo.com','kirit_bellubbi@yahoo.com');